# config.yaml
version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(asctime)-20s %(name)-10s %(levelname)s:%(message)s"
    datefmt: "%d-%b-%y %H:%M:%S"
  complex:
    format: "%(asctime)-20s %(name)-10s %(levelname)s %(message)s"
    datefmt: "%d-%b-%y %H:%M:%S"  
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: complex
    filename: helpers/logging.log
    mode: w
loggers:
  root:
    handlers: [console, file_handler]
    propagate: true